### ISSUE TITLE
Controller mappings not saving

### ISSUE THREAD

**Issue by arithmaldor** [MiSTer-devel/MemTest_MiSTer#1]
Trying to save controller settings for a SNES controller (just the arrow keys) and they work until I exit the core, then settings are not saved, even after using the "save settings" menu option.

**Comment by sorgelig** [comment]
It works with my joysticks. So probably you does something wrong.

**Comment by sorgelig** [comment]
This core doesn't support joystick.
It's service core. It requires the keyboard.
