### ISSUE TITLE
Support built-in RAM

### ISSUE THREAD

**Issue by djvj1** [MiSTer-devel/MemTest_MiSTer#2]
Could you add support for testing the built-in RAM?

**Comment by sorgelig** [comment]
which one? DDR3?

**Comment by djvj1** [comment]
Yes precisely

**Comment by sorgelig** [comment]
FPGA is allowed to access only half of DDR3 memory because second half is used by Linux. Frequency of DDR3 is fixed to 800MHz.
So, it will be pretty much useless test.

**Comment by djvj1** [comment]
I was just thinking more in the lines of an ability to error check on-board ram from errors. I recently had bad add-on SDRAM and noticed the current memtest errors on every sector when the add-on ram is removed. At first I thought my on-board was bad as well. Could be a way for users to know their de10 is error-free in that department. No big deal, just throwing it out there if it was easy to include.

**Comment by sorgelig** [comment]
anyway, it's not related to memtest which is for SDRAM only.
