### ISSUE TITLE
20190907 shows errors on 32MB XS v1.1

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/MemTest_MiSTer#3]
I've loaded the old version, and it show no errors at 167MHz
New version shows more errors than the passed tests.
Clearly, the support for the new modules has a regression.

**Comment by apolkosnik** [comment]
Additionally, when the memory module is removed the test still shows successes (on both versions), though the failures are piling up so fast that there are graphical glitches.

I think that an area that displays the details about the attached memory modules would be great. Especially things like capacity e.g. 256Mbit (32MBytes).

**Comment by sorgelig** [comment]
1) New memtest uses new SDRAM controller which is more reliable than old one (it's mentioned in release notes). You see more errors on new version? This is good. This is supposed to be this way. Less fake "167MHz passed" tests.
2) Green number is not "successes". It's number of rounds. Only zeros in red number means success.
3) Teal number 0-3 in the second row shows the detected memory module code 0-None/1-32MB/2-64MB/3-128MB
