### ISSUE TITLE
Is MemTest supposed to run without the memody module?

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/MemTest_MiSTer#4]
I removed my memory module and MemTest runs just fine, though show the red digits in a glitchy manner, as if not waiting for the vertical blank. 

It would be great to see which are it's testing, and have some more details. Otherwise, it has the entertainment value of a log fireplace. ;-)

**Comment by sorgelig** [comment]
teal colored 0 in the left of the second row means no memory detected.

**Comment by scatteredfrog** [comment]
When I run memtest I get a black screen -- zero video output. Is there some kind of a delay before there's a video signal or something??

**Comment by sorgelig** [comment]
Video should work normally as in other cores.

**Comment by farhanjiwani** [comment]
> When I run memtest I get a black screen -- zero video output. Is there some kind of a delay before there's a video signal or something??

I'm having the same issue. I have the RBF in the root dir of my SD card, am I missing anything else?

**Comment by farhanjiwani** [comment]
I added the update.sh script and ran it and after that, MemTest worked like a charm

**Comment by asturur** [comment]
Sorry if i ask again because the answer isn't clear.
I have a faulty board, but i also get errors all over the place with no module installed ( and a 0 on the second row ).
Is this normal?
Is the test meaningfull with no add on ram?
(and i also see the glitchy numbers)

**Comment by sorgelig** [comment]
if you see teal colored 0 in the left of the second row then any other numbers are irrelevant.

**Comment by asturur** [comment]
ok this means, with no module, the test does not make sense. Thanks.
