### ISSUE TITLE
Incomplete description of memtest screen

### ISSUE THREAD

**Issue by MarcinOrlowski** [MiSTer-devel/MemTest_MiSTer#5]
The README miss description of middle row's digi shown on the left ("3"). I assume it's type (size) or memory module?

![memtest](https://user-images.githubusercontent.com/8041294/71235028-c5b7ce00-22af-11ea-832f-5ca2453eee46.jpg)

**Comment by sorgelig** [comment]
Yes.
0 - none
1 - 32mb
2 - 64mb
3 - 128mb
