### ISSUE TITLE
Auto-mode should be default

### ISSUE THREAD

**Issue by MarcinOrlowski** [MiSTer-devel/MemTest_MiSTer#6]
For a sake of future users, let me suggest auto-mode (that tries to detect memory's supported operating freq) to be default setting. It would save a lot of time and frustration, esp. for people just starting. For now it kicks in at 167 (at least in my case) which was too high, so there was just errors and I was suspecting faulty memory module for a longer moment (unless I found this can be tweaked manually).

**Comment by sorgelig** [comment]
I have plans to do it.

**Comment by sebnete** [comment]
hi 
i have received my new XS-D 128 MB, and tested it in auto mode at 130mhz during 3 hours, without errors.
tomorrow morning, i have tested it in manual mode at 140mhz during 2 hours and now the ram is defect! and in auto mode, it runs only at 70mhz with errors in memtest
overheat have killed it, please insert a warning message in your tool, that a prolonged stress in manual mode at 140mhz can destroy definitively the ram board!

thanks

**Comment by sorgelig** [comment]
This is wrong assumption. My MiSTer works about 18-20hours per day and often with cores using SDRAM. 
What happened to your SDRAM module is unclear. Sometimes bad contact on connector may lower the frequency. Or may be something else.

**Comment by sorgelig** [comment]
Auto-mode on start is implemented.

**Comment by sebnete** [comment]
it working very well at 130mhz during 3 hours in auto mode before i use
manual mode at 140mhz during 2hours.
manual mode do stop the test if too many errors appear, make a routine to
protect the module in manual mode
long stress test do overheat, and my module do not pass any test at any
speed now!
it is dead

**Comment by sorgelig** [comment]
Memtest besides the obvious test for max speed has another test - burn-in test. So your module didn't pass the burn-in test.
As i've told above fully working module cannot be broken. Your module originally had hidden defect which revealed after burn-in test. 
Fully working module should work indefinite (ok, some finite time like several years if it's matter) time without degradation.

Also it's highly recommended to use active cooling (fan), especially if board is inside the case.
