### ISSUE TITLE
Dump out which RAM locations are failing?

### ISSUE THREAD

**Issue by dnwe** [MiSTer-devel/MemTest_MiSTer#8]
For the failed test cycles, would it be possible to have the memtest dump out which RAM locations were failing to a file or something? If so, it would be useful when working out if it there is a short (and which two address lines are shorted) or whether a particular chip is bad etc.

**Comment by sorgelig** [comment]
Memtest is simple state-machine cpu-less core.
For advanced tests it's better to make another core with CPU so it will display more detailed info and provide more tests.
Such task is definitely not for this core.

**Comment by dnwe** [comment]
Ok no problem. Thanks for the clarification
